variables:
  SITE_URL: "https://mkdocs-template-7ce39f.gitlab.io/"

pages:
  stage: deploy
  image: python:latest
  script:
    - echo "Mise à jour de mkdocs.yml avec l'URL du site"
    - envsubst < mkdocs.yml > mkdocs_tmp.yml && mv mkdocs_tmp.yml mkdocs.yml  # Utilisation de envsubst pour remplacer SITE_URL
    - pip install -r requirements.txt 
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'