site_name: Documentation Template
site_url: http://127.0.0.1:8000/

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  palette:    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom
      accent: custom

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/light_mode
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/dark_mode
        name: Switch to system preference
      primary: custom
      accent: custom
  font:
    text: Montserrat
    
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - print-site:
      toc_title: 'Table of Contents'
      add_full_urls: true
      path_to_pdf: "assets/site.pdf"
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/templates/custom_banner.tpl"
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"


extra:
    abstract: This is a report about a topic
    banner_message: "Save this page using File > Print > Save as PDF"
    alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: French
      link: /fr/
      lang: fr

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons