site_name: Documentation Template
site_url: http://127.0.0.1:8000/
site_description: Template for MkDocs
site_author: Lucas Leyronas
repo_url: ""
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  palette:    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom
      accent: custom

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/light_mode
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/dark_mode
        name: Switch to system preference
      primary: custom
      accent: custom
  font:
    text: Montserrat
  features:
      - navigation.instant
      - navigation.instant.progress
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.prune 
      - navigation.top
      - search.suggest
      - search.highlight
      - search.share
      - announce.dismiss


extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - print-site:
      toc_title: 'Table of Contents'
      add_full_urls: true
      path_to_pdf: "assets/site.pdf"
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/templates/custom_banner.tpl"
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"


extra:
  abstract: This is a report about a topic
  banner_message: "Save this page using File > Print > Save as PDF"
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: French
      link: /fr/
      lang: fr
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  version:
    provider: mike
copyright: |
          &copy 2024 Precia Molen. All rights reserved.
          The content and images on this website are the property of Precia Molen and may not be used without permission

