site_name: My MkDocs Material Documentation
site_url: https://sitename.example
theme:
  name: material
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - print-site