site_name: Documentation Template
site_url: http://127.0.0.1:8000/

theme:
  name: material
  custom_dir: overrides
  palette:
    - primary: custom
    - accent: custom
    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - print-site:
      toc_title: 'Table of Contents'
      add_full_urls: true
      path_to_pdf: "assets/site.pdf"
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/templates/custom_banner.tpl"
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"


extra:
    abstract: This is a report about a topic
    banner_message: "Save this page using File > Print > Save as PDF"